require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CocktailsController do

  # This should return the minimal set of attributes required to create a valid
  # Cocktail. As you add validations to Cocktail, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { name: 'Sazerac' } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CocktailsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all cocktails as @cocktails" do
      cocktail = create(:cocktail)
      get :index, {}, valid_session
      assigns(:cocktails).should eq([cocktail])
    end
  end

  describe "GET show" do
    it "assigns the requested cocktail as @cocktail" do
      cocktail = Cocktail.create! valid_attributes
      get :show, {:id => cocktail.to_param}, valid_session
      assigns(:cocktail).should eq(cocktail)
    end
  end

  describe "GET new" do
    it "assigns a new cocktail as @cocktail" do
      get :new, {}, valid_session
      assigns(:cocktail).should be_a_new(Cocktail)
    end
  end

  describe "GET edit" do
    it "assigns the requested cocktail as @cocktail" do
      cocktail = Cocktail.create! valid_attributes
      get :edit, {:id => cocktail.to_param}, valid_session
      assigns(:cocktail).should eq(cocktail)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Cocktail" do
        expect {
          post :create, {:cocktail => valid_attributes}, valid_session
        }.to change(Cocktail, :count).by(1)
      end

      it "assigns a newly created cocktail as @cocktail" do
        post :create, {:cocktail => valid_attributes}, valid_session
        assigns(:cocktail).should be_a(Cocktail)
        assigns(:cocktail).should be_persisted
      end

      it "redirects to the created cocktail" do
        post :create, {:cocktail => valid_attributes}, valid_session
        response.should redirect_to(Cocktail.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cocktail as @cocktail" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cocktail.any_instance.stub(:save).and_return(false)
        post :create, {:cocktail => {  }}, valid_session
        assigns(:cocktail).should be_a_new(Cocktail)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Cocktail.any_instance.stub(:save).and_return(false)
        post :create, {:cocktail => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cocktail" do
        cocktail = Cocktail.create! valid_attributes
        # Assuming there are no other cocktails in the database, this
        # specifies that the Cocktail created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Cocktail.any_instance.should_receive(:update).with({ "name" => "This name" })
        put :update, {:id => cocktail.to_param, :cocktail => { "name" => "This name" }}, valid_session
      end

      it "assigns the requested cocktail as @cocktail" do
        cocktail = Cocktail.create! valid_attributes
        put :update, {:id => cocktail.to_param, :cocktail => valid_attributes}, valid_session
        assigns(:cocktail).should eq(cocktail)
      end

      it "redirects to the cocktail" do
        cocktail = Cocktail.create! valid_attributes
        put :update, {:id => cocktail.to_param, :cocktail => valid_attributes}, valid_session
        response.should redirect_to(cocktail)
      end
    end

    describe "with invalid params" do
      it "assigns the cocktail as @cocktail" do
        cocktail = Cocktail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cocktail.any_instance.stub(:save).and_return(false)
        put :update, {:id => cocktail.to_param, :cocktail => {  }}, valid_session
        assigns(:cocktail).should eq(cocktail)
      end

      it "re-renders the 'edit' template" do
        cocktail = Cocktail.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Cocktail.any_instance.stub(:save).and_return(false)
        put :update, {:id => cocktail.to_param, :cocktail => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cocktail" do
      cocktail = Cocktail.create! valid_attributes
      expect {
        delete :destroy, {:id => cocktail.to_param}, valid_session
      }.to change(Cocktail, :count).by(-1)
    end

    it "redirects to the cocktails list" do
      cocktail = Cocktail.create! valid_attributes
      delete :destroy, {:id => cocktail.to_param}, valid_session
      response.should redirect_to(cocktails_url)
    end
  end

end
